
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.1
 * Query Engine version: 55ae170b1ced7fc6ed07a15f110549408c501bb3
 */
Prisma.prismaVersion = {
  client: "7.4.1",
  engine: "55ae170b1ced7fc6ed07a15f110549408c501bb3"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.FirmScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  logoUrl: 'logoUrl',
  primaryColor: 'primaryColor',
  physicalAddress: 'physicalAddress',
  linkedInUrl: 'linkedInUrl',
  googleReviewsUrl: 'googleReviewsUrl',
  bio: 'bio',
  heroMediaUrl: 'heroMediaUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  accentColor: 'accentColor',
  backgroundColor: 'backgroundColor',
  fontColor: 'fontColor',
  showAgencyBranding: 'showAgencyBranding',
  logoScale: 'logoScale',
  borderRadius: 'borderRadius',
  bioFontFamily: 'bioFontFamily',
  bioFontSize: 'bioFontSize',
  firmNameFontFamily: 'firmNameFontFamily',
  firmNameFontSize: 'firmNameFontSize',
  firmNameFontWeight: 'firmNameFontWeight',
  isColorLinked: 'isColorLinked',
  isFontLinked: 'isFontLinked',
  bioFontColor: 'bioFontColor',
  firmNameFontColor: 'firmNameFontColor',
  memberCardBgColor: 'memberCardBgColor',
  memberPhotoSpacing: 'memberPhotoSpacing',
  showMemberNarrative: 'showMemberNarrative',
  isMemberCardColorLinked: 'isMemberCardColorLinked',
  cardShadowIntensity: 'cardShadowIntensity',
  portfolioListStyle: 'portfolioListStyle',
  showSearchBar: 'showSearchBar',
  teamListStyle: 'teamListStyle',
  viewLayoutMode: 'viewLayoutMode',
  tombstoneInfoBgColor: 'tombstoneInfoBgColor',
  tombstoneLayout: 'tombstoneLayout',
  tombstoneMaxWidth: 'tombstoneMaxWidth',
  tombstoneMediaBgColor: 'tombstoneMediaBgColor',
  tombstoneMetricsBgColor: 'tombstoneMetricsBgColor',
  tombstoneNarrativeBgColor: 'tombstoneNarrativeBgColor',
  tombstonePadding: 'tombstonePadding'
};

exports.Prisma.InvitationScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  role: 'role',
  firmId: 'firmId',
  isUsed: 'isUsed',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  role: 'role',
  firmId: 'firmId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  name: 'name',
  resetToken: 'resetToken',
  resetTokenExpires: 'resetTokenExpires'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  role: 'role',
  email: 'email',
  imageURL: 'imageURL',
  firmId: 'firmId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  bio: 'bio',
  firmIds: 'firmIds',
  heroMediaUrl: 'heroMediaUrl',
  linkedInUrl: 'linkedInUrl',
  phoneNumber: 'phoneNumber',
  sortOrder: 'sortOrder',
  userId: 'userId',
  department: 'department',
  managerId: 'managerId'
};

exports.Prisma.AssetFileScalarFieldEnum = {
  id: 'id',
  name: 'name',
  content: 'content',
  type: 'type',
  teamMemberId: 'teamMemberId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DealScalarFieldEnum = {
  id: 'id',
  address: 'address',
  assetType: 'assetType',
  strategy: 'strategy',
  purchaseAmount: 'purchaseAmount',
  financedAmount: 'financedAmount',
  stillImageURL: 'stillImageURL',
  generatedVideoURL: 'generatedVideoURL',
  isPublic: 'isPublic',
  capRate: 'capRate',
  sqFt: 'sqFt',
  firmId: 'firmId',
  teamMemberId: 'teamMemberId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  arv: 'arv',
  context: 'context',
  financingType: 'financingType',
  images: 'images',
  investmentOverview: 'investmentOverview',
  rehabAmount: 'rehabAmount',
  teamMemberIds: 'teamMemberIds',
  sortOrder: 'sortOrder'
};

exports.Prisma.ActivityLogScalarFieldEnum = {
  id: 'id',
  type: 'type',
  title: 'title',
  timestamp: 'timestamp',
  firmId: 'firmId',
  dealId: 'dealId',
  userId: 'userId',
  memberId: 'memberId',
  performedByEmail: 'performedByEmail'
};

exports.Prisma.TaskScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  status: 'status',
  priority: 'priority',
  assigneeId: 'assigneeId',
  dueDate: 'dueDate',
  firmId: 'firmId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.UserRole = exports.$Enums.UserRole = {
  FIRM_ADMIN: 'FIRM_ADMIN',
  USER: 'USER',
  SYSTEM_ADMIN: 'SYSTEM_ADMIN'
};

exports.AssetType = exports.$Enums.AssetType = {
  INDUSTRIAL: 'INDUSTRIAL',
  RETAIL: 'RETAIL',
  MULTIFAMILY: 'MULTIFAMILY',
  SF: 'SF',
  OFFICE: 'OFFICE',
  HOTEL: 'HOTEL',
  HOSPITALITY: 'HOSPITALITY',
  MIXED_USE: 'MIXED_USE',
  LAND: 'LAND'
};

exports.Strategy = exports.$Enums.Strategy = {
  BUY_AND_HOLD: 'BUY_AND_HOLD',
  FIX_FLIP: 'FIX_FLIP',
  VALUE_ADD: 'VALUE_ADD',
  CORE: 'CORE',
  STABILIZED: 'STABILIZED',
  OPPORTUNISTIC: 'OPPORTUNISTIC'
};

exports.Prisma.ModelName = {
  Firm: 'Firm',
  Invitation: 'Invitation',
  User: 'User',
  TeamMember: 'TeamMember',
  AssetFile: 'AssetFile',
  Deal: 'Deal',
  ActivityLog: 'ActivityLog',
  Task: 'Task'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
